wazo-platform/wazo-dird

CHANGELOG.md, integration_tests/assets/etc/wazo-dird/conf.d/asset.wazo_users_multiple_wazo.yml, integration_tests/suite/helpers/config.py, integration_tests/suite/test_conference_contacts.py, wazo_dird/plugins/conference_backend/api.yml, wazo_dird/plugins/conference_backend/http.py, wazo_dird/plugins/conference_backend/plugin.py, wazo_dird/plugins/conference_backend/schemas.py, wazo_dird/plugins/conference_backend/tests/test_schemas.py
This branch adds the ability to list conference rooms that are configured on an wazo-platform and that are available to a user.
this resource is meant to be used in conjunction with the `/directories/<profile>/sources` which lists the sources that are available to the user.
=> WAZO-756 conference list

integration_tests/Makefile, integration_tests/assets/docker-compose.documentation.override.yml, integration_tests/suite/test_documentation.py, integration_tests/test-requirements.txt, wazo_dird/plugins/conference_backend/api.yml
reason: openapi-spec-validator catches more errors
=> use openapi-spec-validator instead of swagger-validator

CHANGELOG.md, integration_tests/suite/test_wazo_user_contacts.py, wazo_dird/plugins/wazo_user_backend/api.yml, wazo_dird/plugins/wazo_user_backend/schemas.py
The "id" is required to be able to set the contact as a favorite because when
doing a GET /lookup the source_entry_id is mapped to the "id" column
=> wazo user contact list: add the id field

debian/wazo-dird.service
dird used to call xivo-confgen to get its configuration but not anymore
=> dird does not need to start after confgend

integration_tests/suite/test_personal.py, wazo_dird/plugins/personal/http.py, wazo_dird/plugins/personal_service/plugin.py
if xivo_user_uuid field is deprecated and should not be used, I chose the
metadata['uuid'] field to allow any wazo-auth user to have contacts, not only
pbx users which in most cases is the same.
If a token has no metadata['uuid'], which is not possible at the moment, a 401
error is returned instead of listing all personal contacts.
=> personal: use the uuid from metadata

integration_tests/assets/confd_data/asset.wazo_users_late_confd/run_confd, integration_tests/suite/test_wazo_user_backend.py
Why:
* Sometimes, the test would fail because late_confd would start too
early in the test
=> integration tests: fix race condition for late_confd

wazo_dird/plugins/csv_backend/plugin.py, wazo_dird/plugins/csv_backend/tests/test_csv_plugin.py, wazo_dird/plugins/source_result.py
If a column is configured in searched_columns, unique_column,
first_match_columns and that column does not exist dird will ignore it during a
lookup and log an error message.
=> WAZO-1375 csv backend: log errors when an absent column is configured

integration_tests/assets/etc/wazo-dird/conf.d/asset.half_broken.yml, integration_tests/docker/broken-plugins/setup.py, integration_tests/docker/broken-plugins/xivo_dird_broken_plugins/broken_backend.py, integration_tests/suite/helpers/config.py, integration_tests/suite/test_core_functionality.py, wazo_dird/plugins/reverse_service/plugin.py
Why:
* If one reverse source fails, it would cancel other reverse sources,
because `[]` is not `None`.
How:
* The tests try to reverse lookup on a broken source first, then on a
valid source. The code does not guarantee 100% that the broken source runs
first, but the lock coupled with time.sleep should be enough.
=> reverse: dont cancel other reverse upon failure

wazo_dird/plugins/conference_backend/plugin.py
Why:
* Easier to see why a contact is not returned
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1743
=> conferences: add debug logging

integration_tests/suite/test_graphql.py, wazo_dird/plugins/graphql/plugin.py
Why:
* Querying { me { userUuid } } would return an Unauthorized error, even
if the ACL dird.graphql.me is allowed.
* This was probably introduced when switching to graphene
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/33
=> graphql: fix root query detection

integration_tests/suite/test_graphql.py, wazo_dird/plugins/graphql/plugin.py
Why:
* `__schema` serves for the GraphQL API documentation and should not
require more authorization than OpenAPI documentation.
=> graphql: skip authentication for query __schema

integration_tests/suite/test_graphql.py, wazo_dird/plugins/graphql/resolver.py, wazo_dird/plugins/graphql/schema.py
Why:
* Distinguish contacts from a conference or wazo_user backend
=> graphql: add contact field backend

integration_tests/suite/test_google_http.py, wazo_dird/plugins/wazo_user_backend/tests/test_schemas.py, wazo_dird/schemas.py
Why:
* Default values would be incorrect for connecting to a real wazo
contact source.
=> wazo user backend: fix default values for auth/confd without https

alembic/versions/1bb9ba1188f4_add_wazo_reverse_lookup_fields.py, wazo_dird/plugins/config_service/plugin.py
Why:
* An application may want to know who is the caller from call logs.
=> wazo backend: add default reverse lookup on "exten" field

integration_tests/suite/test_dird_phonebook_backend.py, wazo_dird/plugins/base_plugins.py
the old behavior returned all results with None, what overwritten the
result for other sources
=> fix default implementation of match_all

CHANGELOG.md, alembic/versions/29d00094fd68_google_office365_avoid_duplicate_number_.py, integration_tests/suite/test_auto_create.py, wazo_dird/plugins/config_service/plugin.py, wazo_dird/plugins/google_backend/api.yml, wazo_dird/plugins/google_backend/services.py, wazo_dird/plugins/google_backend/tests/test_service.py, wazo_dird/plugins/office365_backend/api.yml, wazo_dird/plugins/office365_backend/plugin.py, wazo_dird/plugins/office365_backend/services.py, wazo_dird/plugins/office365_backend/tests/test_office365_plugin.py
Why:
* avoid duplication mobile phone numbers
=> Pull request for WAZO-2177-duplicate-mobile

wazo_dird/bus.py
Why:
* standardize with other daemons
=> bus: rename callback wrapper

alembic/versions/29d00094fd68_google_office365_avoid_duplicate_number_.py
Why:
* Office365 sources may not have a "phone" format column
=> upgrade office356: accept missing default format column

integration_tests/suite/test_graphql.py
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/50
=> test: update deprecated acls property

integration_tests/test-requirements-for-tox.txt
why: to have the latest docker-compose
=> use docker-compose from binary instead of python

integration_tests/test-requirements-for-tox.txt, requirements.txt
why: if not pinned, pip install latest version (2.1.0) which is
incompatible with flask 1.0.2 from buster
=> pin itsdangerous version

integration_tests/test-requirements-for-tox.txt
this avoids pulling a broken version when flasks will get installed
=> WAZO-2723 requirements: pin markupsafe

setup.py, wazo_dird/plugins/api/api.yml
=> doc: use wazo-platform.org instead of wazo.community url

integration_tests/suite/test_auto_create.py, integration_tests/suite/test_personal.py
Why:
* was used during transition from xivo -> wazo-headers
* no longer in use = dead code
=> WAZO-3004: remove `downstream_exchange_declare`

wazo_dird/plugins/phonebook/api.yml
why: redefines the global version found in API plugin,and breaks our reference documentation
=> remove swagger version in phonebook API plugin

integration_tests/suite/test_database.py, wazo_dird/database/queries/phonebook.py
* contact phonebook selector in phonebook contact dao relies on inexistant column. Fixed by changing to a subquery filter.
* the function implementing this filter is only used in one class, so I folded it back in as a private method.
* The fixed code path is not currently used, as the phonebook is always queried first with the key(id or uuid), and then the uuid of the retrieved phonebook is used to filter on contacts.
=> Phonebook id contact fix

alembic/versions/a3a7212e29b8_source_add_phonebook_uuid.py
when using the source name, was not limiting match to the same tenant scope, leading to sources matched to phonebooks not respecting the foreign key constraint and breaking the migration.
=> Fixed phonebook source migration

integration_tests/suite/test_favorites.py, integration_tests/suite/test_personal.py
why: it's now the recommended way to use docker compose
=> use docker compose without hyphen command

alembic/versions/042a2ba167c0_add_firstname_and_lastname_to_display.py, integration_tests/suite/test_auto_create.py, wazo_dird/plugins/config_service/plugin.py
the default displays auto generated for each tenant now includes the firstname and lastname columns
the goal is to allow an application more flexibility
=> displays: add columns to the default display

requirements.txt, wazo_dird/plugins/conference_backend/schemas.py, wazo_dird/plugins/csv_backend/schemas.py, wazo_dird/plugins/csv_ws_backend/schemas.py, wazo_dird/plugins/displays/schemas.py, wazo_dird/plugins/google_backend/schemas.py, wazo_dird/plugins/ldap_backend/schemas.py, wazo_dird/plugins/office365_backend/schemas.py, wazo_dird/plugins/personal_backend/schemas.py, wazo_dird/plugins/phonebook/schemas.py, wazo_dird/plugins/phonebook_backend/schemas.py, wazo_dird/plugins/profiles/schemas.py, wazo_dird/plugins/sources/schemas.py, wazo_dird/plugins/wazo_user_backend/schemas.py, wazo_dird/schemas.py
This change uses the Bookworm version of marshmallow to reduce the scope of changes that are going to happen when doing the upgrade
=> Use marshmallow version 3.18.0 from Bookworm

bin/wazo-dird-init-db
- psycopg <2.9 (bullseye): when autocommit=True, the context manager is a noop
- psycopg >= 2.9 (bookworm): context manager always open a transaction
and it's imcompatible with CREATE DATABASE
=> remove no-op transaction with psycopg2
