- Dockerfile
- debian/wazo-dird.postinst
- debian/wazo-dird.service
- wazo_dird/config.py
since buster /var/run is a now a symlink to /run
> use /run instead of /var/run

- tox.ini
Depends-On: https://github.com/wazo-platform/wazo-dird/pull/25
> tox: fix syntax

- integration_tests/assets/confd_data/asset.wazo_users/1.1/conferences
- integration_tests/suite/test_conference_backend.py
- integration_tests/suite/test_database.py
- integration_tests/suite/test_office365_backend.py
- wazo_dird/plugins/conference_backend/plugin.py
- wazo_dird/plugins/ldap_backend/tests/test_ldap_plugin.py
- wazo_dird/plugins/wazo_user_backend/plugin.py
- wazo_dird/plugins/wazo_user_backend/tests/test_wazo_user_backend.py
- wazo_dird/tests/test_plugin_manager.py
make conference search accent insensitive
make wazo_user_backend search accent insensitive
> Pull request for WAZO-1079-search-unaccent

- wazo_dird/plugins/wazo_user_backend/api.yml
- wazo_dird/plugins/wazo_user_backend/schemas.py
Depends-on: https://github.com/wazo-platform/wazo-confd/pull/43
Depends-on: https://github.com/wazo-platform/wazo-dird-client/pull/9
> backend wazo contacts: allow to pass many uuid to get users

- .tx/config
- README.md
- wazo_dird/plugins/api/api.yml
openapi: remove unused AcceptLanguage
clean transifex config
> Pull request for clean-transifex

- CHANGELOG.md
- README.md
CHANGELOG: use standard markdown syntax
add missing changelog for contact uuid
> Pull request for update-changelog-19-17

- alembic/versions/3966fb49ce71_update_office365_default_number_columns.py
- wazo_dird/plugins/config_service/plugin.py
- wazo_dird/plugins/office365_backend/api.yml
- wazo_dird/plugins/office365_backend/plugin.py
- wazo_dird/plugins/office365_backend/services.py
- wazo_dird/plugins/office365_backend/tests/test_office365_plugin.py
alembic: add office365 default values
office365: fix OpenAPI spec and add description
office365: fix unhandled exception
config_service: fix office365 default config
office365_backend: aggregate all contact numbers in a field
office365_backend: remove search with term
> WAZO-1483: fix office365 search

- integration_tests/suite/test_google.py
- integration_tests/suite/test_google_contacts.py
- wazo_dird/plugins/google_backend/plugin.py
- wazo_dird/plugins/google_backend/services.py
- wazo_dird/plugins/google_backend/tests/test_service.py
Extract and expose more info from the Google source:
> WAZO-1081: Google more contact info

- wazo_dird/plugins/wazo_user_backend/plugin.py
- wazo_dird/plugins/wazo_user_backend/tests/test_wazo_user_backend.py
A few small improvements I needed when working on wazo-dird. The modified exception catcher was hiding the KeyError I introduced while adding logs.
> Pull request for wazo-backend-debug

- alembic/script.py.mako
- alembic/versions/40298554e752_update_wazo_default_reverse.py
- wazo_dird/plugins/config_service/plugin.py
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1737
> add reverse lookup for wazo source

- alembic/versions/0542e068b5ef_migrate_confd_config_without_ssl.py
- integration_tests/assets/confd_data/asset.wazo_users/1.1/conferences
- integration_tests/suite/helpers/config.py
- integration_tests/suite/test_auto_create.py
- integration_tests/suite/test_conference_backend.py
- integration_tests/suite/test_wazo_user_backend.py
- wazo_dird/plugins/config_service/plugin.py
- wazo_dird/plugins/favorites_service/tests/test_favorites_service.py
- wazo_dird/plugins/lookup_service/tests/test_lookup.py
- wazo_dird/plugins/wazo_user_backend/tests/test_schemas.py
- wazo_dird/schemas.py
update directories config to use confd without ssl
test: fix python segfault
> Pull request for WAZO-1747-confd-http

- Dockerfile
- debian/wazo-dird.service
- wazo_dird/config.py
- wazo_dird/main.py
- wazo_dird/tests/test_main.py
reason: systemd restart remove monit usage based on pid file
> remove usage of PID file and use systemd options

- wazo_dird/bus.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/30
> bus: use correct policy for publishing

- CHANGELOG.md
- integration_tests/suite/base_dird_integration_test.py
- integration_tests/suite/test_conference_backend.py
- integration_tests/suite/test_office365_backend.py
- integration_tests/suite/test_wazo_user_backend.py
- wazo_dird/plugins/base_plugins.py
- wazo_dird/plugins/conference_backend/plugin.py
- wazo_dird/plugins/google_backend/plugin.py
- wazo_dird/plugins/graphql/resolver.py
- wazo_dird/plugins/office365_backend/plugin.py
- wazo_dird/plugins/reverse_service/plugin.py
- wazo_dird/plugins/sample_backend/plugin.py
- wazo_dird/plugins/wazo_user_backend/plugin.py
- wazo_dird/plugins/wazo_user_backend/tests/test_wazo_user_backend.py
For the reviewer: I tested Google backend, but not Microsoft
> Pull request for WAZO-2078-improve-graphql-internal-requests

- alembic/versions/4f76dc8ffb57_add_missing_fk_cascade.py
- integration_tests/assets/etc/wazo-dird/conf.d/asset.all_routes.yml
- integration_tests/docker/broken-plugins/setup.py
- integration_tests/docker/broken-plugins/xivo_dird_broken_plugins/broken_service.py
- integration_tests/suite/helpers/base.py
- integration_tests/suite/test_auto_create.py
- integration_tests/suite/test_bus.py
- integration_tests/suite/test_personal.py
- wazo_dird/bus.py
- wazo_dird/plugins/cleanup_service/plugin.py
- wazo_dird/plugins/config_service/plugin.py
- wazo_dird/plugins/service_discovery_service/plugin.py
Also fixes WAZO-2146 otherwise the tests won't pass
> Wazo 2147 miss autocreate

- wazo_dird/plugins/google_backend/services.py
- wazo_dird/plugins/office365_backend/services.py
when a user has not logged into office or google
when an administrator has not configured office or google applications
> office/google: do not use logger.error in normal situations

- wazo_dird/plugin_manager.py
- wazo_dird/source_manager.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/81
> add namespace parameter to on_missing_entrypoints

- CHANGELOG.md
- integration_tests/assets/docker-compose.wazo_users_late_confd.override.yml
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/wait_strategy.py
- integration_tests/suite/test_authentication.py
- integration_tests/suite/test_auto_create.py
- integration_tests/suite/test_graphql.py
- wazo_dird/plugins/status/api.yml
- wazo_dird/plugins/status/plugin.py
why: to be used by integration tests
> Pull request for wait-on-dird

- integration_tests/test-requirements-for-tox.txt
- requirements.txt
- wazo_dird/database/schemas.py
- wazo_dird/plugins/conference_backend/schemas.py
- wazo_dird/plugins/csv_backend/schemas.py
- wazo_dird/plugins/csv_ws_backend/schemas.py
- wazo_dird/plugins/google_backend/schemas.py
- wazo_dird/plugins/ldap_backend/schemas.py
- wazo_dird/plugins/office365_backend/schemas.py
- wazo_dird/plugins/phonebook_service/plugin.py
- wazo_dird/plugins/profiles/schemas.py
- wazo_dird/plugins/wazo_user_backend/schemas.py
- wazo_dird/schemas.py
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/93
> Wazo-2638: Migration of wazo-dird from Marshmallow 3.0.0b14 to 3.10.0

- integration_tests/assets/docker-compose.yml
- wazo_dird/plugins/graphql/plugin.py
Depends-On: https://github.com/wazo-platform/wazo-auth-client/pull/28
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/96
> graphql: is_valid can now raise more exceptions

- integration_tests/docker/broken-plugins/xivo_dird_broken_plugins/broken_service.py
- integration_tests/suite/test_auto_create.py
- integration_tests/suite/test_bus.py
- integration_tests/suite/test_favorites.py
- integration_tests/suite/test_personal.py
- wazo_dird/bus.py
- wazo_dird/config.py
- wazo_dird/controller.py
- wazo_dird/plugins/cleanup_service/plugin.py
- wazo_dird/plugins/config_service/plugin.py
- wazo_dird/plugins/service_discovery_service/plugin.py
- wazo_dird/tests/test_controller.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/52
> WAZO-2512 Bus consume on headers instead of topic (routing key)

- integration_tests/docker/broken-plugins/xivo_dird_broken_plugins/broken_service.py
- integration_tests/suite/test_auto_create.py
- integration_tests/suite/test_personal.py
- wazo_dird/bus.py
- wazo_dird/controller.py
- wazo_dird/plugins/cleanup_service/plugin.py
- wazo_dird/plugins/favorites_service/plugin.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/59
> WAZO-2505: dird events

- debian/control
- debian/rules
- zuul.yaml
> Pull request for zuul-debian-packaging

- wazo_dird/plugins/api/api.yml
depends-on: https://github.com/wazo-platform/wazo-platform.org/pull/613
> [WAZO-3270] Add logo to spec

- CHANGELOG.md
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/fixtures/http.py
- integration_tests/suite/helpers/utils.py
- integration_tests/suite/test_conference_backend.py
- integration_tests/suite/test_csv_backend.py
- integration_tests/suite/test_csv_ws_backend.py
- integration_tests/suite/test_dird_phonebook_backend.py
- integration_tests/suite/test_office365_backend.py
- integration_tests/suite/test_phonebook_http.py
- integration_tests/suite/test_wazo_user_backend.py
- wazo_dird/helpers.py
- wazo_dird/plugins/base_plugins.py
- wazo_dird/plugins/phonebook_backend/api.yml
- wazo_dird/plugins/phonebook_backend/plugin.py
- wazo_dird/plugins/phonebook_backend/schemas.py
- wazo_dird/plugins/source_result.py
- wazo_dird/plugins/source_service/plugin.py
https://wazo-dev.atlassian.net/browse/WAZO-3267
depends-on: #167
> Wazo 3267 phonebook source schema

- wazo_dird/plugins/phonebook/http.py
- wazo_dird/plugins/phonebook_deprecated/http.py
Only handled exceptions enter this except block. If it is handled it should not be logged
> phonebook: remove tracebacks from logs

- integration_tests/suite/helpers/base.py
- integration_tests/suite/test_phonebook_http.py
- integration_tests/test-requirements-for-tox.txt
- wazo_dird/config.py
- wazo_dird/controller.py
- wazo_dird/database/models.py
- wazo_dird/database/queries/base.py
- wazo_dird/database/queries/phonebook.py
- wazo_dird/database/queries/source.py
- wazo_dird/exception.py
- wazo_dird/helpers.py
- wazo_dird/plugins/base_plugins.py
- wazo_dird/plugins/phonebook/http.py
- wazo_dird/plugins/phonebook/schemas.py
- wazo_dird/plugins/phonebook_backend/api.yml
- wazo_dird/plugins/phonebook_backend/http.py
- wazo_dird/plugins/phonebook_backend/plugin.py
- wazo_dird/plugins/phonebook_backend/schemas.py
- wazo_dird/plugins/phonebook_deprecated/http.py
- wazo_dird/plugins/phonebook_service/plugin.py
- wazo_dird/plugins/phonebook_service/tests/test_phonebook_service.py
- wazo_dird/plugins/source_service/plugin.py
- wazo_dird/source_manager.py
- wazo_dird/utils.py
https://wazo-dev.atlassian.net/browse/WAZO-3271
> Wazo 3271 phonebook source

- integration_tests/docker/wazo-dird-test.Dockerfile
https://wazo-dev.atlassian.net/browse/WAZO-3342
> Updated integration test dockerfile editable install commands

- CHANGELOG.md
- alembic/versions/3b2bfef244e7_remove_orphaned_phonebook_sources.py
- alembic/versions/a3a7212e29b8_source_add_phonebook_uuid.py
- integration_tests/suite/helpers/fixtures/db.py
- integration_tests/suite/helpers/fixtures/http.py
- integration_tests/suite/helpers/utils.py
- integration_tests/suite/test_database.py
- integration_tests/suite/test_phonebook_http.py
- wazo_dird/auth.py
- wazo_dird/controller.py
- wazo_dird/database/models.py
- wazo_dird/database/queries/source.py
- wazo_dird/exception.py
- wazo_dird/helpers.py
- wazo_dird/plugin_manager.py
- wazo_dird/plugins/base_plugins.py
- wazo_dird/plugins/phonebook/plugin.py
- wazo_dird/plugins/phonebook_backend/http.py
- wazo_dird/plugins/phonebook_backend/plugin.py
- wazo_dird/plugins/phonebook_backend/schemas.py
- wazo_dird/plugins/phonebook_backend/tests/test_dird_phonebook_backend.py
- wazo_dird/plugins/phonebook_service/plugin.py
- wazo_dird/plugins/phonebook_service/tests/test_phonebook_service.py
- wazo_dird/plugins/source_service/plugin.py
- wazo_dird/tests/test_controller.py
depends-on: https://github.com/wazo-platform/wazo-dird-client/pull/24
> [WAZO-3372] [WAZO-3385] phonebook sync

- integration_tests/assets/confd_data/asset.wazo_users/1.1/users
- integration_tests/suite/test_wazo_user_backend.py
- wazo_dird/plugins/wazo_user_backend/plugin.py
- wazo_dird/plugins/wazo_user_backend/tests/test_wazo_user_backend.py
https://wazo-dev.atlassian.net/browse/WP-920
> Wp 920 full name lookup

- alembic/versions/7c49d771407a_update_wazo_internal_source_directory_.py
- wazo_dird/plugins/config_service/plugin.py
https://wazo-dev.atlassian.net/browse/WP-1187
> Wp 1187 full name search migration

- wazo_dird/plugins/api/api.yml
- wazo_dird/plugins/phonebook/api.yml
- wazo_dird/plugins/phonebook_deprecated/api.yml
Quick fixes of phonebook openapi doc
> Phonebook openapi improvements

- etc/wazo-dird/config.yml
- wazo_dird/config.py
why: easier to troubleshooting
> config: add application_name for db_uri config

- integration_tests/suite/helpers/base.py
- integration_tests/suite/test_config.py
- wazo_dird/http.py
- wazo_dird/http_server.py
- wazo_dird/plugins/graphql/plugin.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/141
> Pull request for WP-1540-module-auth-verifier-refactor

- debian/wazo-dird.dirs
- debian/wazo-dird.service
- etc/rsyslog.d/99-wazo-dird.conf
> WAZO-3682: disable logs in rsyslog

- wazo_dird/http_server.py
> HTTP server: apply cheroot patch

- CHANGELOG.md
- integration_tests/suite/test_phonebook.py
- wazo_dird/plugins/phonebook/http.py
- **phonebook: no errors is good news**
- **phonebook: successful import yields 201**
> fix phonebook contact import nothing created

- integration_tests/suite/test_graphql.py
- wazo_dird/plugins/graphql/plugin.py
- wazo_dird/plugins/graphql/resolver.py
- wazo_dird/plugins/graphql/schema.py
This PR is just to let the CI run on the branch
> Multiple reverse rebased

- .pre-commit-config.yaml
- pyproject.toml
- wazo_dird/auth.py
- wazo_dird/plugin_helpers/confd_client_registry.py
- wazo_dird/plugin_helpers/self_sorting_service.py
- wazo_dird/plugin_helpers/tenant.py
- wazo_dird/plugin_helpers/tests/test_confd_client_registry.py
- wazo_dird/plugin_helpers/tests/test_self_sorting_service.py
- wazo_dird/plugins/config/http.py
- wazo_dird/plugins/config/plugin.py
- wazo_dird/plugins/config_service/plugin.py
- **typing: type plugin_helpers**
- **typing: force stricter typing**
> some more typing
